version: '3.8'

services:
  nestapp:
    build: NGiulianoNissero/nestmodulo4:latest
    ports:
      - "3001:3005"
    env_file:
      - .development.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .development.env
  
volumes:
  pgdata: